### ISSUE TITLE
Doesn't work with platformio-atom-ide-terminal or atom-term3

### ISSUE THREAD

**Issue by nwaywood** [t9md/atom-focus-pane-or-panel#2]
[platformio-atom-ide-terminal](https://github.com/platformio/platformio-atom-ide-terminal) and [atom-term3](https://github.com/Floobits/atom-term3) seems to be the two main packages for embedding a terminal within atom.

I tried added the following keymaps:

```
'.platform-darwin .platformio-ide-terminal':
    'ctrl-j': 'focus-pane-or-panel:focus-below'
    'ctrl-k': 'focus-pane-or-panel:focus-above'

'.platform-darwin .term3':
    'ctrl-j': 'focus-pane-or-panel:focus-below'
    'ctrl-k': 'focus-pane-or-panel:focus-above'
    'ctrl-h': 'focus-pane-or-panel:focus-left'
    'ctrl-l': 'focus-pane-or-panel:focus-right'
```

but neither set of keybindings works.

From [this issue](https://github.com/t9md/atom-vim-mode-plus/issues/486) in vmp I know that this package is a low priority for you so I'd be happy to submit a PR. But I don't have much experience with Atom package development so I would need some guidance from you to make a PR.

Thanks for all your amazing work :)

**Comment by t9md** [comment]
Source code is very small, I have no special guidance other than basic atom's package creation.

You need to know basic background this package is based on.
- Atom have workspace
- Workspace contains
  - workspace-center workspace: can hold multiple pane and paneItems on each pane
    - normally pane item is editor
    - when you open two editor tab, it means one pane contains two pane items(editor).
  - panel: can hold single item on each panel
  - dock: can hold multiple pane and pane items as workspace-center

- What this package is doing is
  - try normal focus change command (`window:focus-pane-above`)
  - If fail, then assume there is some panel then try to focus panel on same direction.
  - If fail, then assume there is some dock then try to focus dock on same direction.

- There is no **defined** way to **focus** panel, I assume panel item have `focus()` function.
- Why I chose this is just `tree-view` have that methods(but `tree-view` is now dock item from Atom-v1.17).

https://github.com/t9md/atom-focus-pane-or-panel/blame/master/lib/main.coffee#L65


## At this point of writing I noticed I might be misunderstanding your question!!

You successfully can focus **to** these terminal and then want to focus back **from** these terminal tab?
In that case, investigate keymap issue, you first can try invoke command directly from command-palette.

**Comment by nwaywood** [comment]
Sorry for not being more clear. 

You are correct, I can change to these terminals but can't focus back from them. And it does seem to be a keymap issue, it works when executing the commands from the command-palette.

I have tried a bunch of different selectors for the keymap:

- `'.term3':`
- `'.platform-darwin .term3 .terminal':`
- `'.platform-darwin .term3 atom-text-editor':`
- `'.platform-darwin .term3':`

But none of them apply the keymap (when I use `cmd-.` to inspect mappings, the mappings for this package are always greyed out).

I assume this must be possible and I just don't know how to choose selectors, any advice on this?

**Comment by t9md** [comment]
I'll try to see issue your reported by myself from now.

**Comment by t9md** [comment]
Did tried, and I too can't map it, it seems terminal app has it's own keybinding and normal keystroke (except special one like `ctrl-p` ) seems not propagated to Atom's keybinding system.

Before you open this issue, you can try with very simple custom keymap to work, then try to evaluate this `'focus-pane-or-panel:focus-below'` specific command work.

This is NOT my package specific issue.

**Comment by t9md** [comment]
You can open and search issue on term3 or term2 or term1(?) to find out similar keymap issue.
If not, then ask them to how to achieve custom keymap on terminal, that's the simple and straight forward things you can do.

**Comment by nwaywood** [comment]
Ok thanks
